### ISSUE TITLE
Stormpath integration - update doc

### ISSUE THREAD

**Issue by DarrenRatcliffe** [cdaniel/atlas2#118]
This is more a question than an issue:

The Stormpath API closes down in August with instructions to switch to OKTA. Stormpath is closed for new subscriptions so at present it isn't possible to use your code 'As-Is' unless you already have a Stormpath domain. Do you have any plans to refactor the code to use OKTA or similar alternative?

**Comment by cdaniel** [comment]
The wiki is outdated (it's just a couple of pages, shame on me). I'll update it.

The database has been migrated in March 2017. Now, [Auth0](https://auth0.com/) is the provider (commercial tier).
`config.json` required to use auth0 is:
```
{
    "userProvider": {
        "type": "auth0",
        "strategy": "anonymous",
        "auth0": {
          "audience" : "from_auth0__change_me_config_json",
          "issuer" : "from_auth0__change_me_config_json"
        }
    }
}
```

note it is necessary to run `webpack -p` before deploying production code, as auth0 parameters must be injected into client code.

**Comment by DarrenRatcliffe** [comment]
Thanks, so presumably the there will be a need to define a different CUPS service in Cloud Foundry also for production use?

**Comment by cdaniel** [comment]
No, not really. You have to edit `config.json`, run `webpack -p` and you are ready to `cf push`.

**Comment by cdaniel** [comment]
I have updated [the documentation](https://github.com/cdaniel/atlas2/wiki/User-management). Let me know if it is ok for you.

**Comment by DarrenRatcliffe** [comment]
This worked but you also need to set up allowed callback URL in the Auth0 admin page for the domain you set up.

Also I am cf push(ing) to a non-IBM Bluemix CF, they use the standard node.js buildpack and the current one doesn't support you specified version of node within package.json. I needed to change it to 6.10.3 (this is the earliest version of the v6 mainline that it supports) and the cf buildback built it and ran it correctly

**Comment by DarrenRatcliffe** [comment]
also noticing a need to login twice before actually getting logged in. is there something I need to specify in the redirect URL within Auth0 or something?

**Comment by cdaniel** [comment]
I've opened #119 to track buildpacks issue, and #120 to track the login issue. I would appreciate your help on diagnosing #120.
