### ISSUE TITLE
Verify node buildpack is consistent with cf other than delivered by Bluemix

### ISSUE THREAD

**Issue by cdaniel** [cdaniel/atlas2#119]
https://console.bluemix.net/docs/runtimes/nodejs/updates.html#may-5-2017-updated-node-js-buildpack-v3-12

**Comment by DarrenRatcliffe** [comment]
It might be worthwhile also validating the build against the CFF Node.js buildpack https://github.com/cloudfoundry/nodejs-buildpack. It should be possible to use it on Bluemix using the -b parameter in the manifest. All other distributions and service build from source use this as a default for Node.js apps

**Comment by cdaniel** [comment]
Sadly, CF buildpack and Bluemix buildpacks move at different speeds. Currently, [Bluemix](https://console.bluemix.net/docs/runtimes/nodejs/updates.html#latest_updates) defaults to 6.x. stream (6.10.2 precisely), which was already replaced by 6.10.3 in [CF](https://github.com/cloudfoundry/nodejs-buildpack/releases).

Starting with commit d5b799d8d074113924806d2e683b9f89341bf36f, the tool will rely on the default supported major version ('6' for today).
