### ISSUE TITLE
need to login twice before actually getting logged in

### ISSUE THREAD

**Issue by cdaniel** [cdaniel/atlas2#120]
Per report from @DarrentRadcliffe in #118 

The login should work as in the case of https://atlas2.wardleymaps.com/ (single login and getting logged in). I have not touched login mechanism for quite some time, so I have no idea why it behaves this way on your installation, but not on mine. I will have to investigate it.

Do you think you could provide me with an url of that installation? I would like to test that behaviour. Maybe I will be able to compare it with atlas2 and check what is different. What browser do you use?

**Comment by cdaniel** [comment]
At first glance, it looks like a browser refresh issue. Could you check whether refresh works instead of second login? I suspect that browser receives the cookie, stores it, but fails to access it during refresh.

**Comment by cdaniel** [comment]
@darrentradcliffe, I was able to reproduce the issue on Firefox, both social and login/password dialogs are affected. The page is not refreshed as it should.

**Comment by DarrenRatcliffe** [comment]
I closed my browser (chrome) and cleared cache and it still requires logging in twice. It is the same for social and login/password. Atlas is hosted here https://main.apps.eu01.cf.canopy-cloud.com/ if you would like to see?

**Comment by DarrenRatcliffe** [comment]
Can I confirm that the total content in the config.json file should only contain
`{
    "userProvider": {
        "type": "auth0",
        "auth0": {
          "audience" : "<my-token>",
          "issuer" : "<my-domain>"
        }
    }
}`

and nothing else?

**Comment by cdaniel** [comment]
yep, the config is right. For now, the only explanation I have is race condition. AuthService.js, after receiving a token, stores it and refreshes the page.
```
this.setToken(authResult.idToken);
if(this.history){
        this.history.replace('/');
}
```
The token seem to be set correctly (hitting F5 reloads the page and the user is logged in), so the browser for some reason sees no token. Either it is a race condition or a closure problem. I will try to fix this tomorrow.

**Comment by cdaniel** [comment]
Fix proposition https://github.com/cdaniel/atlas2/pull/121

**Comment by cdaniel** [comment]
Considered to be fixed.
