### ISSUE TITLE
npm install fails on ubuntu 14.04.5 LTS

### ISSUE THREAD

**Issue by choeppler** [cdaniel/atlas2#146]
Trying to run atlas2 (commit 00e42767ce85e7f1788d62130e71f7a4f6a46a19) on an ubuntu box (node v6.10.3; npm  v3.10.10) leads to an error during `npm install` (see below). Is a newer version of node required? (According to the [wiki](https://github.com/cdaniel/atlas2/wiki/Dev-Setup) v >= 6.7.0 is expected to work...)

**Error message:**
```npm
~/atlas2$ npm install

> phantomjs-prebuilt@2.1.14 install /home/atlas/atlas2/node_modules/phantomjs-prebuilt
> node install.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/atlas/atlas2/node_modules/fs-extra/lib/index.js:4:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
```

**Comment by cdaniel** [comment]
The application uses phantomjs-prebuilt to run a headless browser required for png rendering. The headless browser is not a node application, but a platform specific binary, and as authors [state](https://www.npmjs.com/package/phantomjs-prebuilt#im-using-an-unsupported-version-of-linux-or-an-arm-processor-i-get-errors-about-unexpected-platform-or-architecture-what-do-i-do):

> We only have binaries available for common OS / processor configurations. Sorry.

That means the tool will not run on arm boxes, unless someone improves phantomjs. I will update the wiki.

**Comment by cdaniel** [comment]
Changes introduced to  https://github.com/cdaniel/atlas2/wiki/Dev-Setup
