### ISSUE TITLE
Docker distribution package

### ISSUE THREAD

**Issue by cdaniel** [cdaniel/atlas2#35]
Make it possible to download and run the tool via docker image

**Comment by bemosior** [comment]
I can help with this. I'll see if I can find time over the next few weeks.

**Comment by cdaniel** [comment]
Thanks, Benjamin!
[Dockerfile](https://github.com/cdaniel/wardleymapstool/blob/master/Dockerfile) from the previous tool version may be useful.

**Comment by cdaniel** [comment]
@bemosior , thank you!
