### ISSUE TITLE
Update wiki for dev setup to state the required version of nodejs

### ISSUE THREAD

**Issue by juliusgb** [cdaniel/atlas2#89]
Hi Chris, @cdaniel 

The second issue that I ran into was the following from phantomjs: "Unexpected token =" in phantomjs. 
- I had to upgrade to the Node version 6.10.3. But I think version 6 might be enough. 
- Can the[Dev Setup Wiki](https://github.com/cdaniel/atlas2/wiki/Dev-Setup) be update to explicitly state the required version of Node?

More details below:

```
C:\var\workshops\wardley-maps\atlas2>npm start
> Atlas2@0.0.2 start C:\var\workshops\wardley-maps\atlas2
> node app.js

[2017-05-14 14:38:38.899] [WARN] tracker-helper - tracking not configured
[2017-05-14 14:38:38.905] [WARN] freshdesk-helper - freshdesk not configured
[2017-05-14 14:38:39.351] [WARN] mongodb-helper - mongoDB service not configured (or configured improperly), defaulting to local database
[2017-05-14 14:38:39.881] [INFO] console - using password
[2017-05-14 14:38:39.881] [INFO] console - using l-p
[2017-05-14 14:38:39.882] [TRACE] user-provider - Using passport anonymous user provider
C:\var\workshops\wardley-maps\atlas2\node_modules\phantom\lib\phantom.js:77
	constructor(args = [], { phantomPath = _phantomjsPrebuilt2.default.path, logger = defaultLogger, logLevel = defaultLogLevel } = {
					 ^
SyntaxError: Unexpected token =
. . .

```
The fix according to these github issues (https://github.com/amir20/phantomjs-node/issues/613 and https://github.com/amir20/phantomjs-node/issues/602) is to upgrade to Node version 6. 
- I upgraded my node version to 6.10.3. 
- Then I was able to start the tool locally.

**Comment by cdaniel** [comment]
Package.json specifies node should be >= 6.7.0, and this is what https://travis-ci.org/cdaniel/atlas2/ uses for testing. I have updated wiki, though.

Thank you for taking time to open those issues. I really need feedback like this!

**Comment by juliusgb** [comment]
No problem. I like the tool.
